// =====================================================
// RELANCEPRO AFRICA - Export Service
// Service d'export PDF et Excel pour les créances, clients et relances
// =====================================================

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { config, getCurrencySymbol, formatCurrencyAmount } from "@/lib/config";
import { Locale } from "@/lib/i18n/config";
import type { Debt, Client, Reminder } from "@/types";

// =====================================================
// TYPES
// =====================================================

export type ExportType = "debts" | "clients" | "reminders";
export type ExportFormat = "pdf" | "excel";

export interface ExportOptions {
  locale?: Locale;
  currency?: string;
  title?: string;
  companyName?: string;
  dateRange?: {
    start: Date;
    end: Date;
  };
  filters?: Record<string, unknown>;
  isDemo?: boolean;
}

export interface ExportData {
  debts?: Array<Debt & { client?: { name: string; email?: string | null; phone?: string | null; company?: string | null } }>;
  clients?: Client[];
  reminders?: Array<Reminder & { client?: { name: string }; debt?: { reference: string | null; amount: number } }>;
}

// =====================================================
// TRANSLATIONS
// =====================================================

const translations = {
  fr: {
    appName: "RelancePro Africa",
    tagline: "Automatisez vos relances clients en Afrique",
    exportDate: "Date d'export",
    page: "Page",
    of: "sur",
    debts: {
      title: "Liste des Créances",
      reference: "Référence",
      client: "Client",
      amount: "Montant",
      paid: "Payé",
      remaining: "Reste",
      dueDate: "Échéance",
      status: "Statut",
      description: "Description",
      statuses: {
        pending: "En attente",
        paid: "Payée",
        partial: "Partielle",
        disputed: "Contestée",
        cancelled: "Annulée",
      },
    },
    clients: {
      title: "Liste des Clients",
      name: "Nom",
      email: "Email",
      phone: "Téléphone",
      company: "Entreprise",
      status: "Statut",
      createdAt: "Date création",
      statuses: {
        active: "Actif",
        inactive: "Inactif",
        blacklisted: "Liste noire",
      },
    },
    reminders: {
      title: "Historique des Relances",
      type: "Type",
      client: "Client",
      debt: "Créance",
      message: "Message",
      status: "Statut",
      date: "Date",
      types: {
        email: "Email",
        whatsapp: "WhatsApp",
      },
      statuses: {
        pending: "En attente",
        sent: "Envoyée",
        failed: "Échec",
        delivered: "Délivrée",
        opened: "Ouverte",
      },
    },
    footer: "Généré par RelancePro Africa",
    total: "Total",
    records: "enregistrements",
  },
  en: {
    appName: "RelancePro Africa",
    tagline: "Automate your customer reminders in Africa",
    exportDate: "Export Date",
    page: "Page",
    of: "of",
    debts: {
      title: "Debts List",
      reference: "Reference",
      client: "Client",
      amount: "Amount",
      paid: "Paid",
      remaining: "Remaining",
      dueDate: "Due Date",
      status: "Status",
      description: "Description",
      statuses: {
        pending: "Pending",
        paid: "Paid",
        partial: "Partial",
        disputed: "Disputed",
        cancelled: "Cancelled",
      },
    },
    clients: {
      title: "Clients List",
      name: "Name",
      email: "Email",
      phone: "Phone",
      company: "Company",
      status: "Status",
      createdAt: "Created At",
      statuses: {
        active: "Active",
        inactive: "Inactive",
        blacklisted: "Blacklisted",
      },
    },
    reminders: {
      title: "Reminders History",
      type: "Type",
      client: "Client",
      debt: "Debt",
      message: "Message",
      status: "Status",
      date: "Date",
      types: {
        email: "Email",
        whatsapp: "WhatsApp",
      },
      statuses: {
        pending: "Pending",
        sent: "Sent",
        failed: "Failed",
        delivered: "Delivered",
        opened: "Opened",
      },
    },
    footer: "Generated by RelancePro Africa",
    total: "Total",
    records: "records",
  },
};

// =====================================================
// UTILITY FUNCTIONS
// =====================================================

/**
 * Format a number with space separators (e.g., "50 000")
 */
function formatNumberWithSpaces(num: number): string {
  return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ");
}

/**
 * Format currency amount for display
 */
function formatCurrency(amount: number, currency: string = "GNF"): string {
  const symbol = getCurrencySymbol(currency);
  return `${formatNumberWithSpaces(Math.round(amount))} ${symbol}`;
}

/**
 * Format date for display
 */
function formatDate(date: Date | string, locale: Locale = "fr"): string {
  const d = typeof date === "string" ? new Date(date) : date;
  return d.toLocaleDateString(locale === "fr" ? "fr-FR" : "en-US", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
}

/**
 * Get status label based on type and status value
 */
function getStatusLabel(
  type: "debt" | "client" | "reminder",
  status: string,
  locale: Locale
): string {
  const t = translations[locale];
  const statusMap: Record<string, string> =
    type === "debt"
      ? t.debts.statuses
      : type === "client"
        ? t.clients.statuses
        : t.reminders.statuses;
  return statusMap[status] || status;
}

// =====================================================
// PDF EXPORT
// =====================================================

/**
 * Generate PDF document
 */
export async function exportToPDF(
  data: ExportData,
  type: ExportType,
  options: ExportOptions = {}
): Promise<Buffer> {
  const locale = options.locale || "fr";
  const currency = options.currency || config.app.currency;
  const t = translations[locale];

  // Create PDF document
  const doc = new jsPDF({
    orientation: type === "reminders" ? "landscape" : "portrait",
    unit: "mm",
    format: "a4",
  });

  // Colors
  const primaryColor: [number, number, number] = [41, 128, 185]; // Blue
  const textColor: [number, number, number] = [44, 62, 80]; // Dark gray
  const lightGray: [number, number, number] = [189, 195, 199];

  // ===== HEADER =====
  // Logo/Brand area
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 35, "F");

  // Company name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(t.appName, 14, 18);

  // Tagline
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(t.tagline, 14, 26);

  // Export date (right side)
  doc.setFontSize(9);
  const exportDateStr = `${t.exportDate}: ${formatDate(new Date(), locale)}`;
  const textWidth = doc.getTextWidth(exportDateStr);
  doc.text(exportDateStr, 196 - textWidth, 18);

  // Company name if provided
  if (options.companyName) {
    doc.text(options.companyName, 196 - doc.getTextWidth(options.companyName), 26);
  }

  // ===== TITLE =====
  doc.setTextColor(...textColor);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  
  const title = type === "debts" ? t.debts.title : type === "clients" ? t.clients.title : t.reminders.title;
  doc.text(title, 14, 48);

  // Date range if provided
  if (options.dateRange) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const rangeText = `${formatDate(options.dateRange.start, locale)} - ${formatDate(options.dateRange.end, locale)}`;
    doc.text(rangeText, 14, 56);
  }

  // ===== DATA TABLE =====
  let startY = options.dateRange ? 62 : 54;

  switch (type) {
    case "debts":
      generateDebtsPDFTable(doc, data.debts || [], startY, t, locale, currency, textColor);
      break;
    case "clients":
      generateClientsPDFTable(doc, data.clients || [], startY, t, locale, textColor);
      break;
    case "reminders":
      generateRemindersPDFTable(doc, data.reminders || [], startY, t, locale, textColor);
      break;
  }

  // ===== FOOTER =====
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Add demo watermark if in demo mode
    if (options.isDemo) {
      // Save current state
      doc.saveGraphicsState?.();
      
      // Add watermark text at center of page (rotated)
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      
      doc.setTextColor(220, 220, 220);
      doc.setFontSize(40);
      doc.setFont("helvetica", "bold");
      
      // Draw diagonal watermark
      doc.text("MODE DÉMO", pageWidth / 2, pageHeight / 2, {
        angle: 45,
        align: "center",
      });
      
      // Restore state
      doc.restoreGraphicsState?.();
      
      // Add demo notice at bottom of page
      doc.setTextColor(255, 150, 0);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      const demoNotice = "⚠️ Document généré en mode démonstration - RelancePro Africa";
      doc.text(demoNotice, 14, 274);
    }
    
    // Footer line
    doc.setDrawColor(...lightGray);
    doc.line(14, 280, 196, 280);

    // Footer text
    doc.setFontSize(8);
    doc.setTextColor(...textColor);
    doc.setFont("helvetica", "normal");
    doc.text(t.footer, 14, 286);

    // Page number
    const pageText = `${t.page} ${i} ${t.of} ${pageCount}`;
    doc.text(pageText, 196 - doc.getTextWidth(pageText), 286);
  }

  // Return as Buffer
  const pdfOutput = doc.output("arraybuffer");
  return Buffer.from(pdfOutput);
}

/**
 * Generate debts table for PDF
 */
function generateDebtsPDFTable(
  doc: jsPDF,
  debts: Array<Debt & { client?: { name: string; email?: string | null; phone?: string | null; company?: string | null } }>,
  startY: number,
  t: typeof translations.fr,
  locale: Locale,
  currency: string,
  textColor: [number, number, number]
): void {
  const tableData = debts.map((debt) => [
    debt.reference || "-",
    debt.client?.name || "-",
    formatCurrency(debt.amount, debt.currency || currency),
    formatCurrency(debt.paidAmount, debt.currency || currency),
    formatCurrency(debt.amount - debt.paidAmount, debt.currency || currency),
    formatDate(debt.dueDate, locale),
    getStatusLabel("debt", debt.status, locale),
  ]);

  // Calculate totals
  const totalAmount = debts.reduce((sum, d) => sum + d.amount, 0);
  const totalPaid = debts.reduce((sum, d) => sum + d.paidAmount, 0);
  const totalRemaining = totalAmount - totalPaid;

  autoTable(doc, {
    startY,
    head: [
      [
        t.debts.reference,
        t.debts.client,
        t.debts.amount,
        t.debts.paid,
        t.debts.remaining,
        t.debts.dueDate,
        t.debts.status,
      ],
    ],
    body: tableData,
    foot: [
      [
        { content: t.total, styles: { fontStyle: "bold", halign: "left" } },
        { content: `${debts.length} ${t.records}`, styles: { fontStyle: "bold" } },
        { content: formatCurrency(totalAmount, currency), styles: { fontStyle: "bold" } },
        { content: formatCurrency(totalPaid, currency), styles: { fontStyle: "bold" } },
        { content: formatCurrency(totalRemaining, currency), styles: { fontStyle: "bold" } },
        "",
        "",
      ],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
      halign: "center",
    },
    bodyStyles: {
      textColor,
      fontSize: 8,
    },
    footStyles: {
      fillColor: [236, 240, 241],
      textColor,
      fontSize: 8,
    },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 35 },
      2: { cellWidth: 30, halign: "right" },
      3: { cellWidth: 25, halign: "right" },
      4: { cellWidth: 30, halign: "right" },
      5: { cellWidth: 25, halign: "center" },
      6: { cellWidth: 20, halign: "center" },
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
    margin: { left: 14, right: 14 },
  });
}

/**
 * Generate clients table for PDF
 */
function generateClientsPDFTable(
  doc: jsPDF,
  clients: Client[],
  startY: number,
  t: typeof translations.fr,
  locale: Locale,
  textColor: [number, number, number]
): void {
  const tableData = clients.map((client) => [
    client.name,
    client.email || "-",
    client.phone || "-",
    client.company || "-",
    getStatusLabel("client", client.status, locale),
    formatDate(client.createdAt, locale),
  ]);

  autoTable(doc, {
    startY,
    head: [
      [
        t.clients.name,
        t.clients.email,
        t.clients.phone,
        t.clients.company,
        t.clients.status,
        t.clients.createdAt,
      ],
    ],
    body: tableData,
    foot: [
      [
        { content: t.total, styles: { fontStyle: "bold" } },
        { content: `${clients.length} ${t.records}`, styles: { fontStyle: "bold", colSpan: 5 } },
        "",
        "",
        "",
        "",
      ],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
      halign: "center",
    },
    bodyStyles: {
      textColor,
      fontSize: 8,
    },
    footStyles: {
      fillColor: [236, 240, 241],
      textColor,
      fontSize: 8,
    },
    columnStyles: {
      0: { cellWidth: 35 },
      1: { cellWidth: 45 },
      2: { cellWidth: 35 },
      3: { cellWidth: 35 },
      4: { cellWidth: 20, halign: "center" },
      5: { cellWidth: 20, halign: "center" },
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
    margin: { left: 14, right: 14 },
  });
}

/**
 * Generate reminders table for PDF
 */
function generateRemindersPDFTable(
  doc: jsPDF,
  reminders: Array<Reminder & { client?: { name: string }; debt?: { reference: string | null; amount: number } }>,
  startY: number,
  t: typeof translations.fr,
  locale: Locale,
  textColor: [number, number, number]
): void {
  const tableData = reminders.map((reminder) => [
    t.reminders.types[reminder.type as keyof typeof t.reminders.types] || reminder.type,
    reminder.client?.name || "-",
    reminder.debt?.reference || "-",
    reminder.message.substring(0, 50) + (reminder.message.length > 50 ? "..." : ""),
    getStatusLabel("reminder", reminder.status, locale),
    formatDate(reminder.createdAt, locale),
  ]);

  autoTable(doc, {
    startY,
    head: [
      [
        t.reminders.type,
        t.reminders.client,
        t.reminders.debt,
        t.reminders.message,
        t.reminders.status,
        t.reminders.date,
      ],
    ],
    body: tableData,
    foot: [
      [
        { content: t.total, styles: { fontStyle: "bold" } },
        { content: `${reminders.length} ${t.records}`, styles: { fontStyle: "bold", colSpan: 5 } },
        "",
        "",
        "",
        "",
      ],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
      halign: "center",
    },
    bodyStyles: {
      textColor,
      fontSize: 8,
    },
    footStyles: {
      fillColor: [236, 240, 241],
      textColor,
      fontSize: 8,
    },
    columnStyles: {
      0: { cellWidth: 20, halign: "center" },
      1: { cellWidth: 35 },
      2: { cellWidth: 25 },
      3: { cellWidth: 70 },
      4: { cellWidth: 20, halign: "center" },
      5: { cellWidth: 20, halign: "center" },
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
    margin: { left: 14, right: 14 },
  });
}

// =====================================================
// EXCEL EXPORT
// =====================================================

/**
 * Generate Excel workbook
 */
export async function exportToExcel(
  data: ExportData,
  type: ExportType,
  options: ExportOptions = {}
): Promise<Buffer> {
  const locale = options.locale || "fr";
  const currency = options.currency || config.app.currency;
  const t = translations[locale];

  const workbook = XLSX.utils.book_new();

  switch (type) {
    case "debts":
      addDebtsSheet(workbook, data.debts || [], t, locale, currency, options.isDemo);
      break;
    case "clients":
      addClientsSheet(workbook, data.clients || [], t, locale, options.isDemo);
      break;
    case "reminders":
      addRemindersSheet(workbook, data.reminders || [], t, locale, options.isDemo);
      break;
  }

  // Generate buffer
  const excelBuffer = XLSX.write(workbook, { type: "buffer", bookType: "xlsx" });
  return Buffer.from(excelBuffer);
}

/**
 * Add debts sheet to workbook
 */
function addDebtsSheet(
  workbook: XLSX.WorkBook,
  debts: Array<Debt & { client?: { name: string; email?: string | null; phone?: string | null; company?: string | null } }>,
  t: typeof translations.fr,
  locale: Locale,
  currency: string,
  isDemo?: boolean
): void {
  const headers = [
    t.debts.reference,
    t.debts.client,
    t.debts.amount,
    t.debts.paid,
    t.debts.remaining,
    t.debts.dueDate,
    t.debts.status,
    t.debts.description,
  ];

  const rows = debts.map((debt) => [
    debt.reference || "",
    debt.client?.name || "",
    debt.amount,
    debt.paidAmount,
    debt.amount - debt.paidAmount,
    formatDate(debt.dueDate, locale),
    getStatusLabel("debt", debt.status, locale),
    debt.description || "",
  ]);

  // Add totals row
  const totalAmount = debts.reduce((sum, d) => sum + d.amount, 0);
  const totalPaid = debts.reduce((sum, d) => sum + d.paidAmount, 0);
  rows.push([
    t.total,
    `${debts.length} ${t.records}`,
    totalAmount,
    totalPaid,
    totalAmount - totalPaid,
    "",
    "",
    "",
  ]);

  const worksheet = XLSX.utils.aoa_to_sheet([headers, ...rows]);

  // Set column widths
  worksheet["!cols"] = [
    { wch: 15 }, // Reference
    { wch: 25 }, // Client
    { wch: 15 }, // Amount
    { wch: 15 }, // Paid
    { wch: 15 }, // Remaining
    { wch: 12 }, // Due Date
    { wch: 12 }, // Status
    { wch: 30 }, // Description
  ];

  // Add currency formatting info
  const currencyInfo = `Devise: ${getCurrencySymbol(currency)} (${currency})`;
  XLSX.utils.sheet_add_aoa(worksheet, [[currencyInfo]], { origin: -1 });

  // Add demo watermark if in demo mode
  if (isDemo) {
    XLSX.utils.sheet_add_aoa(worksheet, [
      [""],
      ["⚠️ Document généré en mode démonstration - RelancePro Africa"],
      ["Ce document contient des données de démonstration et ne doit pas être utilisé à des fins professionnelles."],
    ], { origin: -1 });
  }

  XLSX.utils.book_append_sheet(workbook, worksheet, t.debts.title.substring(0, 31));
}

/**
 * Add clients sheet to workbook
 */
function addClientsSheet(
  workbook: XLSX.WorkBook,
  clients: Client[],
  t: typeof translations.fr,
  locale: Locale,
  isDemo?: boolean
): void {
  const headers = [
    t.clients.name,
    t.clients.email,
    t.clients.phone,
    t.clients.company,
    t.clients.status,
    t.clients.createdAt,
  ];

  const rows = clients.map((client) => [
    client.name,
    client.email || "",
    client.phone || "",
    client.company || "",
    getStatusLabel("client", client.status, locale),
    formatDate(client.createdAt, locale),
  ]);

  // Add totals row
  rows.push([t.total, `${clients.length} ${t.records}`, "", "", "", ""]);

  const worksheet = XLSX.utils.aoa_to_sheet([headers, ...rows]);

  // Set column widths
  worksheet["!cols"] = [
    { wch: 25 }, // Name
    { wch: 30 }, // Email
    { wch: 20 }, // Phone
    { wch: 25 }, // Company
    { wch: 12 }, // Status
    { wch: 12 }, // Created At
  ];

  // Add demo watermark if in demo mode
  if (isDemo) {
    XLSX.utils.sheet_add_aoa(worksheet, [
      [""],
      ["⚠️ Document généré en mode démonstration - RelancePro Africa"],
      ["Ce document contient des données de démonstration et ne doit pas être utilisé à des fins professionnelles."],
    ], { origin: -1 });
  }

  XLSX.utils.book_append_sheet(workbook, worksheet, t.clients.title.substring(0, 31));
}

/**
 * Add reminders sheet to workbook
 */
function addRemindersSheet(
  workbook: XLSX.WorkBook,
  reminders: Array<Reminder & { client?: { name: string }; debt?: { reference: string | null; amount: number } }>,
  t: typeof translations.fr,
  locale: Locale,
  isDemo?: boolean
): void {
  const headers = [
    t.reminders.type,
    t.reminders.client,
    t.reminders.debt,
    t.reminders.message,
    t.reminders.status,
    t.reminders.date,
  ];

  const rows = reminders.map((reminder) => [
    t.reminders.types[reminder.type as keyof typeof t.reminders.types] || reminder.type,
    reminder.client?.name || "",
    reminder.debt?.reference || "",
    reminder.message,
    getStatusLabel("reminder", reminder.status, locale),
    formatDate(reminder.createdAt, locale),
  ]);

  // Add totals row
  rows.push([t.total, `${reminders.length} ${t.records}`, "", "", "", ""]);

  const worksheet = XLSX.utils.aoa_to_sheet([headers, ...rows]);

  // Set column widths
  worksheet["!cols"] = [
    { wch: 12 }, // Type
    { wch: 25 }, // Client
    { wch: 15 }, // Debt
    { wch: 50 }, // Message
    { wch: 12 }, // Status
    { wch: 12 }, // Date
  ];

  // Add demo watermark if in demo mode
  if (isDemo) {
    XLSX.utils.sheet_add_aoa(worksheet, [
      [""],
      ["⚠️ Document généré en mode démonstration - RelancePro Africa"],
      ["Ce document contient des données de démonstration et ne doit pas être utilisé à des fins professionnelles."],
    ], { origin: -1 });
  }

  XLSX.utils.book_append_sheet(workbook, worksheet, t.reminders.title.substring(0, 31));
}

// =====================================================
// MULTI-SHEET EXPORT (All data in one file)
// =====================================================

/**
 * Export all data to a single Excel workbook with multiple sheets
 */
export async function exportAllToExcel(
  data: ExportData,
  options: ExportOptions = {}
): Promise<Buffer> {
  const locale = options.locale || "fr";
  const currency = options.currency || config.app.currency;
  const t = translations[locale];

  const workbook = XLSX.utils.book_new();

  // Add all sheets
  if (data.debts && data.debts.length > 0) {
    addDebtsSheet(workbook, data.debts, t, locale, currency);
  }

  if (data.clients && data.clients.length > 0) {
    addClientsSheet(workbook, data.clients, t, locale);
  }

  if (data.reminders && data.reminders.length > 0) {
    addRemindersSheet(workbook, data.reminders, t, locale);
  }

  // Generate buffer
  const excelBuffer = XLSX.write(workbook, { type: "buffer", bookType: "xlsx" });
  return Buffer.from(excelBuffer);
}

// =====================================================
// HELPER FUNCTIONS
// =====================================================

/**
 * Get filename for export
 */
export function getExportFilename(type: ExportType, format: ExportFormat): string {
  const date = new Date().toISOString().split("T")[0];
  return `relancepro_${type}_${date}.${format === "pdf" ? "pdf" : "xlsx"}`;
}

/**
 * Get MIME type for export format
 */
export function getMimeType(format: ExportFormat): string {
  return format === "pdf"
    ? "application/pdf"
    : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
}
